export enum $auditIssue {
  error = 'error',
  passed = 'passed',
  skipped = 'skipped',
  warning = 'warning'
}

export enum $severity {
  critical = 'critical',
  high = 'high',
  info = 'info',
  low = 'low'
}

export enum $auditRuleSkipReason {
  markedAsFalsePositive = 'markedAsFalsePositive',
  none = 'none',
  notSelectedForScanning = 'notSelectedForScanning'
}

export enum $auditRuleNodeSkipReason {
  excludedFromScanning = 'excludedFromScanning',
  stylesCantBeDetermined = 'stylesCantBeDetermined',
  specifiedStylesCantBeDetermined = 'specifiedStylesCantBeDetermined',
  unableToLoadStyleSheet = 'unableToLoadStyleSheet'
}

export enum $accessibilityAuditRules {
  accessible_svg = 'accessible_svg',
  alt_color_convey_information = 'alt_color_convey_information',
  alt_text_include_filename = 'alt_text_include_filename',
  animation = 'animation',
  applet_missing_alt = 'applet_missing_alt',
  applet_missing_body = 'applet_missing_body',
  area_missing_alt = 'area_missing_alt',
  aria_describedby_association = 'aria_describedby_association',
  aria_hidden_false = 'aria_hidden_false',
  aria_labelledby_association = 'aria_labelledby_association',
  aria_labelledby_association_empty_element = 'aria_labelledby_association_empty_element',
  aria_role_dialog = 'aria_role_dialog',
  audio_alternative = 'audio_alternative',
  audio_video_captions = 'audio_video_captions',
  autoplay_audio_video = 'autoplay_audio_video',
  blink_element = 'blink_element',
  broken_same_page_link = 'broken_same_page_link',
  capital_letters_words = 'capital_letters_words',
  captcha_google = 'captcha_google',
  click_verb = 'click_verb',
  color_contrast_aa = 'color_contrast_aa',
  color_contrast_aaa = 'color_contrast_aaa',
  color_contrast_state_pseudo_classes_active = 'color_contrast_state_pseudo_classes_active',
  color_contrast_state_pseudo_classes_focus = 'color_contrast_state_pseudo_classes_focus',
  color_contrast_state_pseudo_classes_hover = 'color_contrast_state_pseudo_classes_hover',
  content_editable_missing_attributes = 'content_editable_missing_attributes',
  contentinfo_landmark_only_one = 'contentinfo_landmark_only_one',
  css_images_convey_information = 'css_images_convey_information',
  duplicated_for_attribute = 'duplicated_for_attribute',
  duplicated_id_attribute = 'duplicated_id_attribute',
  elements_not_allowed_in_head = 'elements_not_allowed_in_head',
  empty_button_description = 'empty_button_description',
  empty_heading = 'empty_heading',
  empty_label_element = 'empty_label_element',
  empty_link_element = 'empty_link_element',
  empty_title_attribute = 'empty_title_attribute',
  fieldset_no_legend = 'fieldset_no_legend',
  flash_content = 'flash_content',
  flickering = 'flickering',
  font_style_italic = 'font_style_italic',
  general_alt = 'general_alt',
  group_elements_name_attribute = 'group_elements_name_attribute',
  h1_must_be = 'h1_must_be',
  h1_only_one = 'h1_only_one',
  headings_hierarchy = 'headings_hierarchy',
  headings_sibling_unique = 'headings_sibling_unique',
  hidden_content = 'hidden_content',
  horizontal_rule = 'horizontal_rule',
  html_lang_attr = 'html_lang_attr',
  identify_input_purpose = 'identify_input_purpose',
  img_adjacent_duplicate_text_link = 'img_adjacent_duplicate_text_link',
  img_alt_duplicate_text_link = 'img_alt_duplicate_text_link',
  img_empty_alt_in_link = 'img_empty_alt_in_link',
  img_empty_alt_with_empty_title = 'img_empty_alt_with_empty_title',
  incorrect_label_placement = 'incorrect_label_placement',
  incorrect_technique_for_hiding_content = 'incorrect_technique_for_hiding_content',
  input_image_missing_alt = 'input_image_missing_alt',
  invalid_attribute_dir_value = 'invalid_attribute_dir_value',
  label_duplicated_content_title = 'label_duplicated_content_title',
  label_implicitly_associated = 'label_implicitly_associated',
  label_inappropriate_association = 'label_inappropriate_association',
  label_visually_hidden_only = 'label_visually_hidden_only',
  legend_first_child_of_fieldset = 'legend_first_child_of_fieldset',
  link_button_space_key = 'link_button_space_key',
  link_with_unclear_purpose = 'link_with_unclear_purpose',
  links_language_destination = 'links_language_destination',
  links_new_window_mark = 'links_new_window_mark',
  links_not_visually_evident_without_color_vision = 'links_not_visually_evident_without_color_vision',
  links_same_content_different_url = 'links_same_content_different_url',
  main_element_only_one = 'main_element_only_one',
  main_landmark_must_be_top_level = 'main_landmark_must_be_top_level',
  meaningful_content_sequence = 'meaningful_content_sequence',
  minimum_font_size = 'minimum_font_size',
  missing_alt_attribute = 'missing_alt_attribute',
  missing_href_on_a = 'missing_href_on_a',
  missing_label = 'missing_label',
  missing_submit_button = 'missing_submit_button',
  misused_aria_on_focusable_element = 'misused_aria_on_focusable_element',
  misused_input_attribute = 'misused_input_attribute',
  misused_required_attribute = 'misused_required_attribute',
  misused_tabindex_attribute = 'misused_tabindex_attribute',
  motion_actuation = 'motion_actuation',
  navigation_landmark_restrictions = 'navigation_landmark_restrictions',
  no_headings = 'no_headings',
  no_meta_http_equiv_refresh = 'no_meta_http_equiv_refresh',
  object_general_alt = 'object_general_alt',
  object_missing_body = 'object_missing_body',
  obsolete_html_attributes = 'obsolete_html_attributes',
  obsolete_html_elements = 'obsolete_html_elements',
  orientation = 'orientation',
  outline_zero = 'outline_zero',
  overlay = 'overlay',
  page_title = 'page_title',
  position_sticky = 'position_sticky',
  positive_tabindex = 'positive_tabindex',
  reflow = 'reflow',
  role_application = 'role_application',
  rtl_content = 'rtl_content',
  select_initial_option = 'select_initial_option',
  table_caption_summary_identical = 'table_caption_summary_identical',
  table_missing_description = 'table_missing_description',
  table_row_and_column_headers = 'table_row_and_column_headers',
  text_color_convey_information = 'text_color_convey_information',
  title_for_abbr = 'title_for_abbr',
  title_iframe = 'title_iframe',
  unclear_anchor_uri = 'unclear_anchor_uri',
  unsupported_aria_on_element = 'unsupported_aria_on_element',
  unsupported_role_on_element = 'unsupported_role_on_element',
  video_audio_descriptions = 'video_audio_descriptions',
  zoom_disabled = 'zoom_disabled'
}

export enum IssueCategory {
  adaptable = 'adaptable',
  aria = 'aria',
  audio = 'audio',
  captcha = 'captcha',
  distinguishable = 'distinguishable',
  embedded_objects = 'embedded_objects',
  forms = 'forms',
  headings = 'headings',
  images = 'images',
  links = 'links',
  operable = 'operable',
  perceivable = 'perceivable',
  robust = 'robust',
  tables = 'tables',
  uncategorized = 'uncategorized',
  understandable = 'understandable',
  videos = 'videos'
}
