export const NAMED_COLORS: readonly string[] = Object.freeze([
  'abbey',
  'acadia',
  'acapulco',
  'aero blue',
  'affair',
  'akaroa',
  'alabaster',
  'albescent white',
  'algae green',
  'alice blue',
  'alizarin crimson',
  'allports',
  'almond frost',
  'almond',
  'alpine',
  'alto',
  'aluminium',
  'amaranth',
  'amazon',
  'amber',
  'americano',
  'amethyst smoke',
  'amethyst',
  'amour',
  'amulet',
  'anakiwa',
  'antique brass',
  'antique bronze',
  'anzac',
  'apache',
  'apple blossom',
  'apple green',
  'apple',
  'apricot peach',
  'apricot white',
  'apricot',
  'aqua deep',
  'aqua forest',
  'aqua haze',
  'aqua island',
  'aqua spring',
  'aqua squeeze',
  'aquamarine blue',
  'aquamarine',
  'arapawa',
  'armadillo',
  'arrowtown',
  'ash',
  'asparagus',
  'asphalt',
  'astra',
  'astral',
  'astronaut blue',
  'astronaut',
  'athens gray',
  'aths special',
  'atlantis',
  'atoll',
  'atomic tangerine',
  'au chico',
  'aubergine',
  'australian mint',
  'avocado',
  'axolotl',
  'azalea',
  'aztec',
  'azure radiance',
  'azure',
  'baby blue',
  'bahama blue',
  'bahia',
  'baja white',
  'bali hai',
  'baltic sea',
  'bamboo',
  'banana mania',
  'bandicoot',
  'barberry',
  'barley corn',
  'barley white',
  'barossa',
  'bastille',
  'battleship gray',
  'bay leaf',
  'bay of many',
  'bazaar',
  'bean  ',
  'beauty bush',
  'beaver',
  'beeswax',
  'beige',
  'bermuda gray',
  'bermuda',
  'beryl green',
  'bianca',
  'big stone',
  'bilbao',
  'biloba flower',
  'birch',
  'bird flower',
  'biscay',
  'bismark',
  'bison hide',
  'bistre',
  'bitter lemon',
  'bitter',
  'bittersweet',
  'bizarre',
  'black bean',
  'black forest',
  'black haze',
  'black marlin',
  'black olive',
  'black pearl',
  'black rock',
  'black rose',
  'black russian',
  'black squeeze',
  'black white',
  'black',
  'blackberry',
  'blackcurrant',
  'blaze orange',
  'bleach white',
  'bleached cedar',
  'blizzard blue',
  'blossom',
  'blue bayoux',
  'blue bell',
  'blue chalk',
  'blue charcoal',
  'blue chill',
  'blue diamond',
  'blue dianne',
  'blue gem',
  'blue haze',
  'blue lagoon',
  'blue marguerite',
  'blue ribbon',
  'blue romance',
  'blue smoke',
  'blue stone',
  'blue violet',
  'blue whale',
  'blue zodiac',
  'blue',
  'blumine',
  'blush pink',
  'blush',
  'bombay',
  'bon jour',
  'bondi blue',
  'bone',
  'bordeaux',
  'bossanova',
  'boston blue',
  'botticelli',
  'bottle green',
  'boulder',
  'bouquet',
  'bourbon',
  'bracken',
  'brandy punch',
  'brandy rose',
  'brandy',
  'breaker bay',
  'brick red',
  'bridal heath',
  'bridesmaid',
  'bright gray',
  'bright green',
  'bright red',
  'bright sun',
  'bright turquoise',
  'brilliant rose',
  'brink pink',
  'bronco',
  'bronze olive',
  'bronze',
  'bronzetone',
  'broom',
  'brown bramble',
  'brown derby',
  'brown pod',
  'brown rust',
  'brown tumbleweed',
  'brown',
  'bubbles',
  'buccaneer',
  'bud',
  'buddha gold',
  'buff',
  'bulgarian rose',
  'bull shot',
  'bunker',
  'bunting',
  'burgundy',
  'burnham',
  'burning orange',
  'burning sand',
  'burnt maroon',
  'burnt orange',
  'burnt sienna',
  'burnt umber',
  'bush',
  'buttercup',
  'buttered rum',
  'butterfly bush',
  'buttermilk',
  'buttery white',
  'cab sav',
  'cabaret',
  'cabbage pont',
  'cactus',
  'cadet blue',
  'cadillac',
  'cafe royale',
  'calico',
  'california',
  'calypso',
  'camarone',
  'camelot',
  'cameo',
  'camouflage green',
  'camouflage',
  'can can',
  'canary',
  'candlelight',
  'candy corn',
  'cannon black',
  'cannon pink',
  'cape cod',
  'cape honey',
  'cape palliser',
  'caper',
  'caramel',
  'cararra',
  'cardin green',
  'cardinal pink',
  'cardinal',
  'careys pink',
  'caribbean green',
  'carissma',
  'carla',
  'carmine',
  'carnaby tan',
  'carnation pink',
  'carnation',
  'carousel pink',
  'carrot orange',
  'casablanca',
  'casal',
  'cascade',
  'cashmere',
  'casper',
  'castro',
  'catalina blue',
  'catskill white',
  'cavern pink',
  'cedar wood finish',
  'cedar',
  'celadon',
  'celery',
  'celeste',
  'cello',
  'celtic',
  'cement',
  'ceramic',
  'cerise red',
  'cerise',
  'cerulean blue',
  'cerulean',
  'chablis',
  'chalet green',
  'chalky',
  'chambray',
  'chamois',
  'champagne',
  'chantilly',
  'charade',
  'chardon',
  'chardonnay',
  'charlotte',
  'charm',
  'chartreuse yellow',
  'chartreuse',
  'chateau green',
  'chatelle',
  'chathams blue',
  'chelsea cucumber',
  'chelsea gem',
  'chenin',
  'cherokee',
  'cherry pie',
  'cherrywood',
  'cherub',
  'chestnut rose',
  'chestnut',
  'chetwode blue',
  'chicago',
  'chiffon',
  'chilean fire',
  'chilean heath',
  'china ivory',
  'chino',
  'chinook',
  'chocolate',
  'christalle',
  'christi',
  'christine',
  'chrome white',
  'cinder',
  'cinderella',
  'cinnabar',
  'cinnamon',
  'cioccolato',
  'citrine white',
  'citron',
  'citrus',
  'clairvoyant',
  'clam shell',
  'claret',
  'classic rose',
  'clay ash',
  'clay creek',
  'clear day',
  'clementine',
  'clinker',
  'cloud burst',
  'cloud',
  'cloudy',
  'clover',
  'cobalt',
  'cocoa bean',
  'cocoa brown',
  'coconut cream',
  'cod gray',
  'coffee bean',
  'coffee',
  'cognac',
  'cola',
  'cold purple',
  'cold turkey',
  'colonial white',
  'comet',
  'como',
  'conch',
  'concord',
  'concrete',
  'confetti',
  'congo brown',
  'congress blue',
  'conifer',
  'contessa',
  'copper canyon',
  'copper rose',
  'copper rust',
  'copper',
  'copperfield',
  'coral red',
  'coral reef',
  'coral tree',
  'coral',
  'corduroy',
  'coriander',
  'cork',
  'corn field',
  'corn harvest',
  'corn',
  'cornflower blue',
  'cornflower lilac',
  'cornflower',
  'corvette',
  'cosmic',
  'cosmos',
  'costa del sol',
  'cotton candy',
  'cotton seed',
  'county green',
  'cowboy',
  'crail',
  'cranberry',
  'crater brown',
  'cream brulee',
  'cream can',
  'cream',
  'creole',
  'crete',
  'crimson',
  'crocodile',
  'crown of thorns',
  'crowshead',
  'cruise',
  'crusoe',
  'crusta',
  'cumin',
  'cumulus',
  'cupid',
  'curious blue',
  'cutty sark',
  'cyan / aqua',
  'cyprus',
  'daintree',
  'dairy cream',
  'daisy bush',
  'dallas',
  'dandelion',
  'danube',
  'dark blue',
  'dark burgundy',
  'dark ebony',
  'dark fern',
  'dark tan',
  'dawn pink',
  'dawn',
  'de york',
  'deco',
  'deep blue',
  'deep blush',
  'deep bronze',
  'deep cerulean',
  'deep cove',
  'deep fir',
  'deep forest green',
  'deep koamaru',
  'deep oak',
  'deep sapphire',
  'deep sea green',
  'deep sea',
  'deep teal',
  'del rio',
  'dell',
  'delta',
  'deluge',
  'denim',
  'derby',
  'desert sand',
  'desert storm',
  'desert',
  'dew',
  'di serria',
  'diesel',
  'dingley',
  'disco',
  'dixie',
  'dodger blue',
  'dolly',
  'dolphin',
  'domino',
  'don juan',
  'donkey brown',
  'dorado',
  'double colonial white',
  'double pearl lusta',
  'double spanish white',
  'dove gray',
  'downriver',
  'downy',
  'driftwood',
  'drover',
  'dull lavender',
  'dune',
  'dust storm',
  'dusty gray',
  'eagle',
  'earls green',
  'early dawn',
  'east bay',
  'east side',
  'eastern blue',
  'ebb',
  'ebony clay',
  'ebony',
  'eclipse',
  'ecru white',
  'ecstasy',
  'eden',
  'edgewater',
  'edward',
  'egg sour',
  'egg white',
  'eggplant',
  'el paso',
  'el salva',
  'electric lime',
  'electric violet',
  'elephant',
  'elf green',
  'elm',
  'emerald',
  'eminence',
  'emperor',
  'empress',
  'endeavour',
  'energy yellow',
  'english holly',
  'english walnut',
  'envy',
  'equator',
  'espresso',
  'eternity',
  'eucalyptus',
  'eunry',
  'evening sea',
  'everglade',
  'faded jade',
  'fair pink',
  'falcon',
  'fall green',
  'falu red',
  'fantasy',
  'fedora',
  'feijoa',
  'fern frond',
  'fern green',
  'fern',
  'ferra',
  'festival',
  'feta',
  'fiery orange',
  'finch',
  'finlandia',
  'finn',
  'fiord',
  'fire bush',
  'fire',
  'firefly',
  'flame pea',
  'flamenco',
  'flamingo',
  'flax smoke',
  'flax',
  'flesh',
  'flint',
  'flirt',
  'flush mahogany',
  'flush orange',
  'foam',
  'fog',
  'foggy gray',
  'forest green',
  'forget me not',
  'fountain blue',
  'frangipani',
  'french gray',
  'french lilac',
  'french pass',
  'french rose',
  'fresh eggplant',
  'friar gray',
  'fringy flower',
  'froly',
  'frost',
  'frosted mint',
  'frostee',
  'fruit salad',
  'fuchsia blue',
  'fuchsia pink',
  'fuego',
  'fuel yellow',
  'fun blue',
  'fun green',
  'fuscous gray',
  'fuzzy wuzzy brown',
  'gable green',
  'gallery',
  'galliano',
  'gamboge',
  'geebung',
  'genoa',
  'geraldine',
  'geyser',
  'ghost',
  'gigas',
  'gimblet',
  'gin fizz',
  'gin',
  'givry',
  'glacier',
  'glade green',
  'go ben',
  'goblin',
  'gold drop',
  'gold sand',
  'gold tips',
  'gold',
  'golden bell',
  'golden dream',
  'golden fizz',
  'golden glow',
  'golden grass',
  'golden sand',
  'golden tainoi',
  'goldenrod',
  'gondola',
  'gordons green',
  'gorse',
  'gossamer',
  'gossip',
  'gothic',
  'governor bay',
  'grain brown',
  'grandis',
  'granite green',
  'granny apple',
  'granny smith apple',
  'granny smith',
  'grape',
  'graphite',
  'gravel',
  'gray asparagus',
  'gray chateau',
  'gray nickel',
  'gray nurse',
  'gray olive',
  'gray suit',
  'gray',
  'green haze',
  'green house',
  'green kelp',
  'green leaf',
  'green mist',
  'green pea',
  'green smoke',
  'green spring',
  'green vogue',
  'green waterloo',
  'green white',
  'green yellow',
  'green',
  'grenadier',
  'guardsman red',
  'gulf blue',
  'gulf stream',
  'gull gray',
  'gum leaf',
  'gumbo',
  'gun powder',
  'gunsmoke',
  'gurkha',
  'hacienda',
  'hairy heath',
  'haiti',
  'half and half',
  'half baked',
  'half colonial white',
  'half dutch white',
  'half spanish white',
  'hampton',
  'harlequin',
  'harp',
  'harvest gold',
  'havelock blue',
  'hawaiian tan',
  'hawkes blue',
  'heath',
  'heather',
  'heathered gray',
  'heavy metal',
  'heliotrope',
  'hemlock',
  'hemp',
  'hibiscus',
  'highland',
  'hillary',
  'himalaya',
  'hint of green',
  'hint of red',
  'hint of yellow',
  'hippie blue',
  'hippie green',
  'hippie pink',
  'hit gray',
  'hit pink',
  'hokey pokey',
  'hoki',
  'holly',
  'hollywood cerise',
  'honey flower',
  'honeysuckle',
  'hopbush',
  'horizon',
  'horses neck',
  'hot cinnamon',
  'hot pink',
  'hot toddy',
  'humming bird',
  'hunter green',
  'hurricane',
  'husk',
  'ice cold',
  'iceberg',
  'illusion',
  'inch worm',
  'indian khaki',
  'indian tan',
  'indigo',
  'indochine',
  'international klein blue',
  'international orange',
  'irish coffee',
  'iroko',
  'iron',
  'ironside gray',
  'ironstone',
  'island spice',
  'ivory',
  'jacaranda',
  'jacarta',
  'jacko bean',
  'jacksons purple',
  'jade',
  'jaffa',
  'jagged ice',
  'jagger',
  'jaguar',
  'jambalaya',
  'janna',
  'japanese laurel',
  'japanese maple',
  'japonica',
  'java',
  'jazzberry jam',
  'jelly bean',
  'jet stream',
  'jewel',
  'jon',
  'jonquil',
  'jordy blue',
  'judge gray',
  'jumbo',
  'jungle green',
  'jungle mist',
  'juniper',
  'just right',
  'kabul',
  'kaitoke green',
  'kangaroo',
  'karaka',
  'karry',
  'kashmir blue',
  'kelp',
  'kenyan copper',
  'keppel',
  'key lime pie',
  'khaki',
  'kidnapper',
  'kilamanjaro',
  'killarney',
  'kimberly',
  'kingfisher daisy',
  'kobi',
  'kokoda',
  'korma',
  'koromiko',
  'kournikova',
  'kumera',
  'la palma',
  'la rioja',
  'las palmas',
  'laser lemon',
  'laser',
  'laurel',
  'lavender blush',
  'lavender gray',
  'lavender magenta',
  'lavender pink',
  'lavender purple',
  'lavender rose',
  'lavender',
  'leather',
  'lemon chiffon',
  'lemon ginger',
  'lemon grass',
  'lemon',
  'light apricot',
  'light orchid',
  'light wisteria',
  'lightning yellow',
  'lilac bush',
  'lilac',
  'lily white',
  'lily',
  'lima',
  'lime',
  'limeade',
  'limed ash',
  'limed oak',
  'limed spruce',
  'linen',
  'link water',
  'lipstick',
  'lisbon brown',
  'livid brown',
  'loafer',
  'loblolly',
  'lochinvar',
  'lochmara',
  'locust',
  'log cabin',
  'logan',
  'lola',
  'london hue',
  'lonestar',
  'lotus',
  'loulou',
  'lucky point',
  'lucky',
  'lunar green',
  'luxor gold',
  'lynch',
  'mabel',
  'macaroni and cheese',
  'madang',
  'madison',
  'madras',
  'magenta / fuchsia',
  'magic mint',
  'magnolia',
  'mahogany',
  'mai tai',
  'maize',
  'makara',
  'mako',
  'malachite',
  'malibu',
  'mallard',
  'malta',
  'mamba',
  'manatee',
  'mandalay',
  'mandy',
  'mandys pink',
  'mango tango',
  'manhattan',
  'mantis',
  'mantle',
  'manz',
  'mardi gras',
  'marigold yellow',
  'marigold',
  'mariner',
  'maroon flush',
  'maroon oak',
  'maroon',
  'marshland',
  'martini',
  'martinique',
  'marzipan',
  'masala',
  'matisse',
  'matrix',
  'matterhorn',
  'mauve',
  'mauvelous',
  'maverick',
  'medium carmine',
  'medium purple',
  'medium red violet',
  'melanie',
  'melanzane',
  'melon',
  'melrose',
  'mercury',
  'merino',
  'merlin',
  'merlot',
  'metallic bronze',
  'metallic copper',
  'meteor',
  'meteorite',
  'mexican red',
  'mid gray',
  'midnight blue',
  'midnight moss',
  'midnight',
  'mikado',
  'milan',
  'milano red',
  'milk punch',
  'millbrook',
  'mimosa',
  'mindaro',
  'mine shaft',
  'mineral green',
  'ming',
  'minsk',
  'mint green',
  'mint julep',
  'mint tulip',
  'mirage',
  'mischka',
  'mist gray',
  'mobster',
  'moccaccino',
  'mocha',
  'mojo',
  'mona lisa',
  'monarch',
  'mondo',
  'mongoose',
  'monsoon',
  'monte carlo',
  'monza',
  'moody blue',
  'moon glow',
  'moon mist',
  'moon raker',
  'morning glory',
  'morocco brown',
  'mortar',
  'mosque',
  'moss green',
  'mountain meadow',
  'mountain mist',
  'mountbatten pink',
  'muddy waters',
  'muesli',
  'mulberry wood',
  'mulberry',
  'mule fawn',
  'mulled wine',
  'mustard',
  'my pink',
  'my sin',
  'mystic',
  'nandor',
  'napa',
  'narvik',
  'natural gray',
  'navajo white',
  'navy blue',
  'nebula',
  'negroni',
  'neon carrot',
  'nepal',
  'neptune',
  'nero',
  'nevada',
  'new orleans',
  'new york pink',
  'niagara',
  'night rider',
  'night shadz',
  'nile blue',
  'nobel',
  'nomad',
  'norway',
  'nugget',
  'nutmeg wood finish',
  'nutmeg',
  'oasis',
  'observatory',
  'ocean green',
  'ochre',
  'off green',
  'off yellow',
  'oil',
  'old brick',
  'old copper',
  'old gold',
  'old lace',
  'old lavender',
  'old rose',
  'olive drab',
  'olive green',
  'olive haze',
  'olive',
  'olivetone',
  'olivine',
  'onahau',
  'onion',
  'opal',
  'opium',
  'oracle',
  'orange peel',
  'orange roughy',
  'orange white',
  'orange',
  'orchid white',
  'orchid',
  'oregon',
  'orient',
  'oriental pink',
  'orinoco',
  'oslo gray',
  'ottoman',
  'outer space',
  'outrageous orange',
  'oxford blue',
  'oxley',
  'oyster bay',
  'oyster pink',
  'paarl',
  'pablo',
  'pacific blue',
  'pacifika',
  'paco',
  'padua',
  'pale canary',
  'pale leaf',
  'pale oyster',
  'pale prim',
  'pale rose',
  'pale sky',
  'pale slate',
  'palm green',
  'palm leaf',
  'pampas',
  'panache',
  'pancho',
  'papaya whip',
  'paprika',
  'paradiso',
  'parchment',
  'paris daisy',
  'paris m',
  'paris white',
  'parsley',
  'pastel green',
  'pastel pink',
  'patina',
  'pattens blue',
  'paua',
  'pavlova',
  'peach cream',
  'peach orange',
  'peach schnapps',
  'peach yellow',
  'peach',
  'peanut',
  'pear',
  'pearl bush',
  'pearl lusta',
  'peat',
  'pelorous',
  'peppermint',
  'perano',
  'perfume',
  'periglacial blue',
  'periwinkle gray',
  'periwinkle',
  'persian blue',
  'persian green',
  'persian indigo',
  'persian pink',
  'persian plum',
  'persian red',
  'persian rose',
  'persimmon',
  'peru tan',
  'pesto',
  'petite orchid',
  'pewter',
  'pharlap',
  'picasso',
  'pickled bean',
  'pickled bluewood',
  'picton blue',
  'pig pink',
  'pigeon post',
  'pigment indigo',
  'pine cone',
  'pine glade',
  'pine green',
  'pine tree',
  'pink flamingo',
  'pink flare',
  'pink lace',
  'pink lady',
  'pink salmon',
  'pink swan',
  'pink',
  'piper',
  'pipi',
  'pippin',
  'pirate gold',
  'pistachio',
  'pixie green',
  'pizazz',
  'pizza',
  'plantation',
  'plum',
  'pohutukawa',
  'polar',
  'polo blue',
  'pomegranate',
  'pompadour',
  'porcelain',
  'porsche',
  'port gore',
  'portafino',
  'portage',
  'portica',
  'pot pourri',
  'potters clay',
  'powder ash',
  'powder blue',
  'prairie sand',
  'prelude',
  'prim',
  'primrose',
  'provincial pink',
  'prussian blue',
  'puce',
  'pueblo',
  'puerto rico',
  'pumice',
  'pumpkin skin',
  'pumpkin',
  'punch',
  'punga',
  'purple heart',
  'purple mountain\'s majesty',
  'purple pizzazz',
  'purple',
  'putty',
  'quarter pearl lusta',
  'quarter spanish white',
  'quicksand',
  'quill gray',
  'quincy',
  'racing green',
  'radical red',
  'raffia',
  'rainee',
  'rajah',
  'rangitoto',
  'rangoon green',
  'raven',
  'raw sienna',
  'raw umber',
  'razzle dazzle rose',
  'razzmatazz',
  'rebel',
  'red beech',
  'red berry',
  'red damask',
  'red devil',
  'red orange',
  'red oxide',
  'red ribbon',
  'red robin',
  'red stage',
  'red violet',
  'red',
  'redwood',
  'reef gold',
  'reef',
  'regal blue',
  'regent gray',
  'regent st blue',
  'remy',
  'reno sand',
  'resolution blue',
  'revolver',
  'rhino',
  'rice cake',
  'rice flower',
  'rich gold',
  'rio grande',
  'ripe lemon',
  'ripe plum',
  'riptide',
  'river bed',
  'rob roy',
  'robin\'s egg blue',
  'rock blue',
  'rock spray',
  'rock',
  'rodeo dust',
  'rolling stone',
  'roman coffee',
  'roman',
  'romance',
  'romantic',
  'ronchi',
  'roof terracotta',
  'rope',
  'rose bud cherry',
  'rose bud',
  'rose fog',
  'rose of sharon',
  'rose white',
  'rose',
  'rosewood',
  'roti',
  'rouge',
  'royal blue',
  'royal heath',
  'royal purple',
  'rum swizzle',
  'rum',
  'russet',
  'russett',
  'rust',
  'rustic red',
  'rusty nail',
  'saddle brown',
  'saddle',
  'saffron mango',
  'saffron',
  'sage',
  'sahara sand',
  'sahara',
  'sail',
  'salem',
  'salmon',
  'salomie',
  'salt box',
  'saltpan',
  'sambuca',
  'san felix',
  'san juan',
  'san marino',
  'sand dune',
  'sandal',
  'sandrift',
  'sandstone',
  'sandwisp',
  'sandy beach',
  'sandy brown',
  'sangria',
  'sanguine brown',
  'santa fe',
  'santas gray',
  'sapling',
  'sapphire',
  'saratoga',
  'satin linen',
  'sauvignon',
  'sazerac',
  'scampi',
  'scandal',
  'scarlet gum',
  'scarlet',
  'scarlett',
  'scarpa flow',
  'schist',
  'school bus yellow',
  'schooner',
  'science blue',
  'scooter',
  'scorpion',
  'scotch mist',
  'screamin\' green',
  'sea buckthorn',
  'sea green',
  'sea mist',
  'sea nymph',
  'sea pink',
  'seagull',
  'seance',
  'seashell peach',
  'seashell',
  'seaweed',
  'selago',
  'selective yellow',
  'sepia black',
  'sepia skin',
  'sepia',
  'serenade',
  'shadow green',
  'shadow',
  'shady lady',
  'shakespeare',
  'shalimar',
  'shamrock',
  'shark',
  'sherpa blue',
  'sherwood green',
  'shilo',
  'shingle fawn',
  'ship cove',
  'ship gray',
  'shiraz',
  'shocking pink',
  'shocking',
  'shuttle gray',
  'siam',
  'sidecar',
  'silk',
  'silver chalice',
  'silver rust',
  'silver sand',
  'silver tree',
  'silver',
  'sinbad',
  'siren',
  'sirocco',
  'sisal',
  'skeptic',
  'sky blue',
  'slate gray',
  'smalt blue',
  'smalt',
  'smoky',
  'snow drift',
  'snow flurry',
  'snowy mint',
  'snuff',
  'soapstone',
  'soft amber',
  'soft peach',
  'solid pink',
  'solitaire',
  'solitude',
  'sorbus',
  'sorrell brown',
  'soya bean',
  'spanish green',
  'spectra',
  'spice',
  'spicy mix',
  'spicy mustard',
  'spicy pink',
  'spindle',
  'spray',
  'spring green',
  'spring leaves',
  'spring rain',
  'spring sun',
  'spring wood',
  'sprout',
  'spun pearl',
  'squirrel',
  'st tropaz',
  'stack',
  'star dust',
  'stark white',
  'starship',
  'steel blue',
  'steel gray',
  'stiletto',
  'stonewall',
  'storm dust',
  'storm gray',
  'stratos',
  'straw',
  'strikemaster',
  'stromboli',
  'studio',
  'submarine',
  'sugar cane',
  'sulu',
  'summer green',
  'sun',
  'sundance',
  'sundown',
  'sunflower',
  'sunglo',
  'sunglow',
  'sunset orange',
  'sunshade',
  'supernova',
  'surf crest',
  'surf',
  'surfie green',
  'sushi',
  'suva gray',
  'swamp green',
  'swamp',
  'swans down',
  'sweet corn',
  'sweet pink',
  'swirl',
  'swiss coffee',
  'sycamore',
  'tabasco',
  'tacao',
  'tacha',
  'tahiti gold',
  'tahuna sands',
  'tall poppy',
  'tallow',
  'tamarillo',
  'tamarind',
  'tan hide',
  'tan',
  'tana',
  'tangaroa',
  'tangerine',
  'tango',
  'tapa',
  'tapestry',
  'tara',
  'tarawera',
  'tasman',
  'taupe gray',
  'taupe',
  'tawny port',
  'te papa green',
  'tea green',
  'tea',
  'teak',
  'teal blue',
  'teal',
  'temptress',
  'tenn',
  'tequila',
  'terracotta',
  'texas rose',
  'texas',
  'thatch green',
  'thatch',
  'thistle green',
  'thistle',
  'thunder',
  'thunderbird',
  'tia maria',
  'tiara',
  'tiber',
  'tickle me pink',
  'tidal',
  'tide',
  'timber green',
  'timberwolf',
  'titan white',
  'toast',
  'tobacco brown',
  'toledo',
  'tolopea',
  'tom thumb',
  'tonys pink',
  'topaz',
  'torch red',
  'torea bay',
  'tory blue',
  'tosca',
  'totem pole',
  'tower gray',
  'tradewind',
  'tranquil',
  'travertine',
  'tree poppy',
  'treehouse',
  'trendy green',
  'trendy pink',
  'trinidad',
  'tropical blue',
  'tropical rain forest',
  'trout',
  'true v',
  'tuatara',
  'tuft bush',
  'tulip tree',
  'tumbleweed',
  'tuna',
  'tundora',
  'turbo',
  'turkish rose',
  'turmeric',
  'turquoise blue',
  'turquoise',
  'turtle green',
  'tuscany',
  'tusk',
  'tussock',
  'tutu',
  'twilight blue',
  'twilight',
  'twine',
  'tyrian purple',
  'ultramarine',
  'valencia',
  'valentino',
  'valhalla',
  'van cleef',
  'vanilla ice',
  'vanilla',
  'varden',
  'venetian red',
  'venice blue',
  'venus',
  'verdigris',
  'verdun green',
  'vermilion',
  'vesuvius',
  'victoria',
  'vida loca',
  'viking',
  'vin rouge',
  'viola',
  'violent violet',
  'violet eggplant',
  'violet red',
  'violet',
  'viridian green',
  'viridian',
  'vis vis',
  'vista blue',
  'vista white',
  'vivid tangerine',
  'vivid violet',
  'voodoo',
  'vulcan',
  'wafer',
  'waikawa gray',
  'waiouru',
  'walnut',
  'wasabi',
  'water leaf',
  'watercourse',
  'waterloo ',
  'wattle',
  'watusi',
  'wax flower',
  'we peep',
  'web orange',
  'wedgewood',
  'well read',
  'west coast',
  'west side',
  'westar',
  'wewak',
  'wheat',
  'wheatfield',
  'whiskey',
  'whisper',
  'white ice',
  'white lilac',
  'white linen',
  'white pointer',
  'white rock',
  'white',
  'wild blue yonder',
  'wild rice',
  'wild sand',
  'wild strawberry',
  'wild watermelon',
  'wild willow',
  'william',
  'willow brook',
  'willow grove',
  'windsor',
  'wine berry',
  'winter hazel',
  'wisp pink',
  'wisteria',
  'wistful',
  'witch haze',
  'wood bark',
  'woodland',
  'woodrush',
  'woodsmoke',
  'woody brown',
  'xanadu',
  'yellow green',
  'yellow metal',
  'yellow orange',
  'yellow sea',
  'yellow',
  'your pink',
  'yukon gold',
  'yuma',
  'zambezi',
  'zanah',
  'zest',
  'zeus',
  'ziggurat',
  'zinnwaldite',
  'zircon',
  'zombie',
  'zorba',
  'zuccini',
  'zumthor'
]);
