export const UNCLEAR_LINK_PHRASES_ENGLISH: Readonly<string[]> = Object.freeze([
  'click here',
  'click this',
  'click to learn more',
  'continue reading',
  'continue',
  'download more information',
  'download',
  'go',
  'here',
  'information',
  'learn more',
  'more info',
  'more information',
  'more',
  'read more',
  'right here',
  'see how it works',
  'see more',
  'start',
  'tap here',
  'this'
]);
